### PR TITLE
backward module

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by mforets** [comment]
still some issues with docs build..

**Comment by mforets** [comment]
idk why the docs is failing really, since `Forward` was already exported. 

@schillic should we make the docs build less strict?

**Comment by schillic** [comment]
I fixed the problem.

**Comment by mforets** [comment]
thanks!

**Comment by mforets** [comment]
This is ready from my side. I plan to address more refactors in subsequent PRs.

**Review by schillic — APPROVED** [review]

**Pull request merged**
