### PR TITLE
Add hybrid lotka-volterra model

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by mforets** [comment]
Note : this branch requires to checkout `LazySets#mforets/union`

**Comment by mforets** [comment]
This plot captures the overapproximation of a Taylor model reach-set using a box (blue) and a zonotope (red). I was interesecting these with B_ext since in order to prove disjointness. As it is seen in the plot, the flowpipe actually has left much earlier, which we can prove either using the zonotope overapprox, or computing a tighter continuous solution eg. by splitting. 

Screenshot from 2020-05-23 14-29-46

**Comment by mforets** [comment]
Here is a sample result:

Screenshot from 2020-05-23 19-07-03
=
Playing with the parameter choices one can get smaller final states; there are mainly 2 options:

- `abs_tol` the initial abs tolerance for the adaptive TMJets algorithm: smaller => more accurate
- `nsplit` the number of sets in which the initial state X0 is split: if it's larger => wrapping effects are smaller so the result is more accurate

For instance the following plot was obtained with `abs_tol=1e-16` and `nsplit=10`:

Screenshot from 2020-05-23 19-23-04


Runtime is 3.3sec and 12.5sec respectively.

**Comment by lbenet** [comment]
Beautiful!

**Comment by mforets** [comment]
The intersection time can be obtained with the following function:

```julia
solz = overapproximate(sol, Zonotope);
intersecting_reachsets = []
for (i, Fi) in enumerate(solz)
    for (j, Xj) in enumerate(Fi)
        !isdisjoint(Xj, B_ext) && push!(intersecting_reachsets, (i, j))
    end
end

times = [tspan(solz[ind[1]][ind[2]]) for ind in intersecting_reachsets];
tmin = minimum(tstart, times)
tmax = maximum(tend, times)
tmax - tmin
```
What it does is, for each flowpipe detect those reach-sets that intersect the outer approximation of the ball. Then takes the minimum (resp. maximum) times so we have a proof for an upper bound on the intersection time.

The results obtained for the settings in my previous comment are 0.21554 and 0.17176 respectively.

**Comment by mforets** [comment]
We can also see that there are flowpipes which never intersected the guard:

```julia
[isdisjoint(s, B_ext) for s in solz]
12-element Array{Bool,1}:
 1
 1
 1
 1
 1
 0
 0
 0
 0
 0
 0
 0
```

Here you see 12 flowpipes because:

- The waiting list initially had 10 sets (since i used `nsplit=10`)
- For the first jump we convexify => add a new element to the waiting list => a new `Flowpipe` is computed
- For the second jump (from inside to outside the ball) we convexify a gain and add a new flowpipe

**Pull request merged**
